services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env.prod
    container_name: pim-api
    restart: always
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:?JWT_SECRET_KEY is required}
      - INTERNAL_SERVICE_TOKEN=${INTERNAL_SERVICE_TOKEN:?INTERNAL_SERVICE_TOKEN is required}
      - ALLOWED_SERVICE_KEYS=${ALLOWED_SERVICE_KEYS:?ALLOWED_SERVICE_KEYS is required}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - NEXT_PUBLIC_API_URL=${PIM_API_URL:?PIM_API_URL is required}
        - NEXT_PUBLIC_WMS_API_URL=${WMS_API_URL:?WMS_API_URL is required}
        - NEXT_PUBLIC_IDENTITY_URL=${IDENTITY_URL:?IDENTITY_URL is required}
    container_name: pim-frontend
    restart: always
    depends_on:
      - api
    networks:
      - default
      - wms_default

networks:
  default:
    name: pmi_default
    external: true
  wms_default:
    external: true
