services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env.prod
    container_name: pim-api
    restart: always
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:?JWT_SECRET_KEY is required}
      - INTERNAL_SERVICE_TOKEN=prod_oms_wms_internal_api_key_must_change
      - ALLOWED_SERVICE_KEYS=prod-service-api-key-must-change

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - NEXT_PUBLIC_API_URL=http://api-pmi.topvnsport.com
        - NEXT_PUBLIC_IDENTITY_URL=http://identity.topvnsport.com
    container_name: pim-frontend
    restart: always
    depends_on:
      - api
    networks:
      - default
      - wms_default

networks:
  default:
    name: pmi_default
    external: true
  wms_default:
    external: true
