from .common import (
    CustomerBase,
    CustomerCreate,
    CustomerUpdate,
    CustomerOut,
    ChannelBase,
    ChannelCreate,
    ChannelUpdate,
    ChannelOut,
    PaginatedCustomers,
    PaginatedChannels,
)
from .auth import (
    ZaloConfigUpdate,
    ZaloConfigOut,
    SendOtpRequest,
    VerifyOtpRequest,
    VerifyOtpResponse,
)
from .order import (
    OrderItemBase,
    OrderItemCreate,
    OrderItemOut,
    FulfillmentOrderBase,
    FulfillmentOrderCreate,
    FulfillmentOrderOut,
    OrderBase,
    OrderCreate,
    OrderOut,
    OrderItemInput,
    OrderCreateInput,
    OrderUpdateInput,
    OrderStatusUpdate,
    FulfillmentStatusUpdate,
)

__all__ = [
    # Customer / Channel
    "CustomerBase",
    "CustomerCreate",
    "CustomerUpdate",
    "CustomerOut",
    "ChannelBase",
    "ChannelCreate",
    "ChannelUpdate",
    "ChannelOut",
    "PaginatedCustomers",
    "PaginatedChannels",
    # Zalo / OTP
    "ZaloConfigUpdate",
    "ZaloConfigOut",
    "SendOtpRequest",
    "VerifyOtpRequest",
    "VerifyOtpResponse",
    # Order / Fulfillment
    "OrderItemBase",
    "OrderItemCreate",
    "OrderItemOut",
    "FulfillmentOrderBase",
    "FulfillmentOrderCreate",
    "FulfillmentOrderOut",
    "OrderBase",
    "OrderCreate",
    "OrderOut",
    "OrderItemInput",
    "OrderCreateInput",
    "OrderUpdateInput",
    "OrderStatusUpdate",
    "FulfillmentStatusUpdate",
]
