# Backend services
upstream identity_api {
    server identity-api:8000;
    keepalive 32;
}

upstream pmi_api {
    server pim-api:8000;
    keepalive 32;
}

upstream oms_api {
    server oms-api:8000;
    keepalive 32;
}

upstream wms_api {
    server wms-api:8000;
    keepalive 32;
}

# Frontend services
upstream identity_frontend {
    server identity-frontend:3000;
}

upstream pmi_frontend {
    server pim-frontend:3000;
}

upstream oms_frontend {
    server oms-frontend:3000;
}

upstream wms_frontend {
    server wms-frontend:3000;
}
