version: '3.8'

services:
  oms_db:
    image: postgres:15-alpine
    container_name: oms_db
    restart: always
    environment:
      POSTGRES_DB: oms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15434:5432"
    volumes:
      - oms_db_data:/var/lib/postgresql/data

  oms_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: oms_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@oms_db:5432/oms_db
    depends_on:
      - oms_db
    networks:
      - default
      - pmi_default
      - wms_default

  oms_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://api-oms.topvnsport.com
        - NEXT_PUBLIC_OMS_API_URL=http://api-oms.topvnsport.com
        - NEXT_PUBLIC_WMS_API_URL=http://api-wms.topvnsport.com
        - NEXT_PUBLIC_IDENTITY_URL=http://identity.topvnsport.com
    container_name: oms_frontend
    restart: always
    depends_on:
      - oms_backend
    networks:
      - default
      - pmi_default
      - wms_default

networks:
  default:
    name: oms_default
    external: true
  pmi_default:
    external: true
  wms_default:
    external: true

volumes:
  oms_db_data:
