# Cửa hàng chính
server {
    listen 80;
    server_name topvnsport.com www.topvnsport.com;
    location / {
        proxy_pass http://web_frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# Hệ thống PMI
server {
    listen 80;
    server_name pmi.topvnsport.com;
    location / {
        proxy_pass http://pim-frontend:3000;
        proxy_set_header Host $host;
    }
}
server {
    listen 80;
    server_name api-pmi.topvnsport.com;
    location / {
        proxy_pass http://pim-api:8000;
        proxy_set_header Host $host;
    }
}

# Hệ thống OMS
server {
    listen 80;
    server_name oms.topvnsport.com;
    location / {
        proxy_pass http://oms_frontend:3001;
        proxy_set_header Host $host;
    }
}
server {
    listen 80;
    server_name api-oms.topvnsport.com;
    location / {
        proxy_pass http://oms_backend:8001;
        proxy_set_header Host $host;
    }
}

# Hệ thống WMS
server {
    listen 80;
    server_name wms.topvnsport.com;
    location / {
        proxy_pass http://wms_frontend:3002;
        proxy_set_header Host $host;
    }
}
server {
    listen 80;
    server_name api-wms.topvnsport.com;
    location / {
        proxy_pass http://wms-api:8002;
        proxy_set_header Host $host;
    }
}

# Identity Service (SSO)
server {
    listen 80;
    server_name identity.topvnsport.com;
    location / {
        proxy_pass http://identity-frontend-prod:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
server {
    listen 80;
    server_name api-identity.topvnsport.com;
    location / {
        proxy_pass http://identity-api-prod:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# Hệ thống MinIO
server {
    listen 80;
    server_name media.topvnsport.com;
    client_max_body_size 100M;
    location / {
        proxy_pass http://pim-minio:9000;
        proxy_set_header Host $host;
    }
}
