services:
  wms-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wms-api
    restart: always
    environment:
      - ENV=production
      - DATABASE_URL=postgresql://${RDS_USER:?RDS_USER is required}:${RDS_PASSWORD:?RDS_PASSWORD is required}@${RDS_HOST:?RDS_HOST is required}:5432/wms?sslmode=${RDS_SSLMODE:?RDS_SSLMODE is required}
      - CORS_ALLOWED_ORIGINS=http://topvnsport.com,http://www.topvnsport.com,http://pmi.topvnsport.com,http://oms.topvnsport.com,http://wms.topvnsport.com
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:?JWT_SECRET_KEY is required}
    networks:
      - default
      - oms_default
      - pmi_default

  wms_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://api-wms.topvnsport.com
        - NEXT_PUBLIC_WMS_API_URL=http://api-wms.topvnsport.com
        - NEXT_PUBLIC_PMI_API_URL=http://api-pmi.topvnsport.com
        - NEXT_PUBLIC_IDENTITY_URL=http://identity.topvnsport.com
    container_name: wms_frontend
    restart: always
    depends_on:
      - wms-api
    networks:
      - default
      - oms_default
      - pmi_default

networks:
  default:
    name: wms_default
    external: true
  oms_default:
    external: true
  pmi_default:
    external: true
