"""add_cost_tax_to_variants

Revision ID: 5a451ed7aa00
Revises: 389100db4264
Create Date: 2026-07-14 22:05:07.510733
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '5a451ed7aa00'
down_revision = '389100db4264'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('default_cost_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('product_variants', sa.Column('default_tax_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'default_tax_rate')
    op.drop_column('product_variants', 'default_cost_price')
    # ### end Alembic commands ###
