"""add_audit_outbox_and_logs

Revision ID: 7885c8173ef9
Revises: e09dc1d43f78
Create Date: 2026-07-12 17:33:41.151192
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '7885c8173ef9'
down_revision = 'e09dc1d43f78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE actor_type_enum AS ENUM ('USER', 'SERVICE')")
    op.execute("CREATE TYPE outbox_status_enum AS ENUM ('PENDING', 'PROCESSING', 'FAILED')")

    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('actor_username', sa.String(length=255), nullable=False),
    sa.Column('actor_type', postgresql.ENUM('USER', 'SERVICE', name='actor_type_enum', create_type=False), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('source_service', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_username'), 'audit_logs', ['actor_username'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_module'), 'audit_logs', ['module'], unique=False)
    op.create_table('audit_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('actor_username', sa.String(length=255), nullable=False),
    sa.Column('actor_type', postgresql.ENUM('USER', 'SERVICE', name='actor_type_enum', create_type=False), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('source_service', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_details', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'FAILED', name='outbox_status_enum', create_type=False), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.String(length=255), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_outbox_created_at'), 'audit_outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_outbox_entity_id'), 'audit_outbox', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_outbox_module'), 'audit_outbox', ['module'], unique=False)
    op.create_index(op.f('ix_audit_outbox_status'), 'audit_outbox', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_outbox_status'), table_name='audit_outbox')
    op.drop_index(op.f('ix_audit_outbox_module'), table_name='audit_outbox')
    op.drop_index(op.f('ix_audit_outbox_entity_id'), table_name='audit_outbox')
    op.drop_index(op.f('ix_audit_outbox_created_at'), table_name='audit_outbox')
    op.drop_table('audit_outbox')
    op.drop_index(op.f('ix_audit_logs_module'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_username'), table_name='audit_logs')
    op.drop_table('audit_logs')

    op.execute("DROP TYPE actor_type_enum")
    op.execute("DROP TYPE outbox_status_enum")
    # ### end Alembic commands ###
