"""remove_stock_column

Revision ID: c9a2d4b80123
Revises: 5a451ed7aa00
Create Date: 2026-07-21 15:45:00.000000
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a2d4b80123'
down_revision = '5a451ed7aa00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('stock', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###
