"""add_outbox_indexes_and_tz

Revision ID: d394d33af157
Revises: e1364ba31fda
Create Date: 2026-07-13 13:08:27.007084
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd394d33af157'
down_revision = 'e1364ba31fda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_outbox', 'locked_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('audit_outbox', 'next_retry_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index('ix_audit_outbox_locked', 'audit_outbox', ['locked_by', 'locked_at'], unique=False, postgresql_where="status = 'PROCESSING'")
    op.create_index('ix_audit_outbox_retry', 'audit_outbox', ['status', 'next_retry_at'], unique=False, postgresql_where="status IN ('PENDING', 'FAILED')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_outbox_retry', table_name='audit_outbox', postgresql_where="status IN ('PENDING', 'FAILED')")
    op.drop_index('ix_audit_outbox_locked', table_name='audit_outbox', postgresql_where="status = 'PROCESSING'")
    op.alter_column('audit_outbox', 'next_retry_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('audit_outbox', 'locked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
