"""Add slug to product

Revision ID: e05b43f4e589
Revises: 119d08c29f15
Create Date: 2026-07-11 09:26:36.085269
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'e05b43f4e589'
down_revision = '119d08c29f15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_channel_attribute_values', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_product_channel_attribute_values_listing_id'), 'product_channel_attribute_values', ['listing_id'], unique=False)
    op.add_column('products', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.alter_column('variant_channel_listings', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_variant_channel_listings_listing_id'), 'variant_channel_listings', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variant_channel_listings_listing_id'), table_name='variant_channel_listings')
    op.alter_column('variant_channel_listings', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_column('products', 'slug')
    op.drop_index(op.f('ix_product_channel_attribute_values_listing_id'), table_name='product_channel_attribute_values')
    op.alter_column('product_channel_attribute_values', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
