"""add_guest_to_actor_type

Revision ID: e1364ba31fda
Revises: bf490866f3d1
Create Date: 2026-07-12 17:52:20.863823
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'e1364ba31fda'
down_revision = 'bf490866f3d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE actor_type_enum ADD VALUE 'GUEST'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
