FROM node:20-alpine

RUN apk add --no-cache git

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

ENV DOCKER_ENV=true

ARG NEXT_PUBLIC_API_URL=http://localhost:18100
ARG NEXT_PUBLIC_IDENTITY_URL=http://localhost:13110

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_IDENTITY_URL=$NEXT_PUBLIC_IDENTITY_URL

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
